interface Words {
  [key: string]: string;
}
const VERBS: Words = {
  "to say": "sagen",
  "to make": "machen",
  "to give": "geben",
  "to come": "kommen",
  "to go": "gehen",
  "to know": "wissen",
  "to see": "sehen",
  "to stand,": "stehen",
  "to find": "finden",
  "to stay": "bleiben",
  "to lie": "liegen",
  "to be called": "heißen",
  "to think": "denken",
  "to take": "nehmen",
  "to do": "tun",
  "to believe": "glauben",
  "to hold": "halten",
  "to name": "nennen",
  "to like": "mögen",
  "to show": "zeigen",
  "to lead": "führen",
  "to speak": "sprechen",
  "to bring": "bringen",
  "to live": "leben",
  "to drive": "fahren",
  "to ask": "fragen",
  "to be valid": "gelten",
  "to place": "stellen",
  "to play": "spielen",
  "to work": "arbeiten",
  "to need": "brauchen",
  "to follow": "folgen",
  "to learn": "lernen",
  "to exist": "bestehen",
  "to understand": "verstehen",
  "to set": "setzen",
  "to get": "bekommen",
  "to begin": "beginnen",
  "to tell": "erzählen",
  "to try": "versuchen",
  "to write": "schreiben",
  "to run": "laufen",
  "to explain": "erklären",
  "to correspond": "entsprechen",
  "to sit": "sitzen",
  "to pull": "ziehen",
  "to shine": "scheinen",
  "to fall": "fallen",
  "to belong": "gehören",
  "to originate": "entstehen",
  "to receive": "erhalten",
  "to meet": "treffen",
  "to search": "suchen",
  "to lay": "legen",
  "to introduce": "vorstellen",
  "to deal": "handeln",
  "to achieve": "erreichen",
  "to carry": "tragen",
  "to manage": "schaffen",
  "to read": "lesen",
  "to lose": "verlieren",
  "to depict": "darstellen",
  "to recognize": "erkennen",
  "to develop": "entwickeln",
  "to talk": "reden",
  "to appear": "aussehen",
  "to form": "bilden",
  "to expect": "erwarten",
  "to affect": "betreffen",
  "to wait": "warten",
  "to pass (about time)": "vergehen",
  "to help": "helfen",
  "to win": "gewinnen",
  "to close": "schließen",
  "to feel": "fühlen",
  "to offer": "bieten",
  "to interest": "interessieren",
  "to remind": "erinnern",
  "to result in": "ergeben",
  "to study": "studieren",
  "to connect": "verbinden",
  "to look at": "ansehen",
  "to lack": "fehlen",
  "to mean": "bedeuten",
  "to compare": "vergleichen",
  "to climb": "steigen",
  "to leave": "verlassen",
};

const ADJECTIVES: Words = {
  whole: "ganz",
  big: "groß",
  good: "gut",
  new: "neu",
  first: "erste",
  long: "lang",
  small: "klein",
  old: "alt",
  tall: "hoch",
  easy: "einfach",
  last: "letzte",
  same: "gleich",
  possible: "möglich",
  own: "eigen",
  beautiful: "schön",
  late: "spät",
  important: "wichtig",
  further: "weitere",
  exactly: "genau",
  young: "jung",
  short: "kurz",
  strong: "stark",
  correct: "richtig",
  diverse: "verschieden",
  certain: "bestimmt",
  better: "besser",
  fast: "schnell",
  secure: "sicher",
  next: "nächste",
  political: "politisch",
  clear: "klar",
  individual: "einzeln",
  "well-known": "bekannt",
  light: "leicht",
  round: "rund",
  free: "frei",
  early: "früh",
  different: "unterschiedlich",
  bad: "schlecht",
  general: "allgemein",
  only: "einzig",
  common: "gemeinsam",
  near: "nah",
  full: "voll",
  direct: "direkt",
  international: "international",
  social: "sozial",
  best: "beste",
  red: "rot",
  open: "offen",
  most: "meiste",
  public: "öffentlich",
  half: "halb",
  porbably: "wahrscheinlich",
  essential: "wesentlich",
  similar: "ähnlich",
  frequent: "häufig",
  black: "schwarz",
  complete: "völlig",
  low: "gering",
  difficult: "schwierig",
  practical: "praktisch",
  personal: "personlich",
  modern: "modern",
  deep: "tief",
  real: "tatsächlich",
  additional: "zusätzlich",
  economic: "wirtschaftlich",
  interesting: "interessant",
  relative: "relativ",
  simultaneous: "gleichzeitig",
  green: "grün",
  white: "weiß",
  entire: "gesamt",
  special: "speziell",
  decisive: "entscheidend",
  narrow: "eng",
  technical: "technisch",
  slow: "langsam",
  constant: "ständig",
  necessary: "notwendig",
  pure: "rein",
  scientific: "wissenschaftlich",
  false: "falsch",
  foreign: "fremd",
  rare: "selten",
  normal: "normal",
  true: "wahr",
  private: "privat",
  dead: "tot",
};

const NOUNS: Words = {
  year: "das Jahr",
  example: "das Beispiel",
  time: "die Zeit",
  woman: "die Frau",
  "human being": "der Mensch",
  child: "das Kind",
  day: "der Tag",
  man: "der Mann",
  country: "das Land",
  question: "die Frage",
  House: "das Haus",
  fall: "der Fall",
  people: "die Leute",
  work: "die Arbeit",
  percent: "das Prozent",
  hand: "das Hand",
  city: "die Stadt",
  part: "der Teil",
  problem: "das Problem",
  world: "die Welt",
  right: "die Recht",
  end: "das Ende",
  school: "die Schule",
  week: "die Woche",
  father: "der Vater",
  page: "die Seite",
  life: "das Leben",
  mother: "die Mutter",
  reason: "der Grund",
  eye: "das Auge",
  word: "das Wort",
  money: "der Geld",
  type: "die Art",
  area: "der Bereich",
  way: "der Weg",
  Hour: "die Stunde",
  name: "der Name",
  history: "die Geschichte",
  society: "die Gesellschaft",
  head: "der Kopf",
  pair: "das Paar",
  possibility: "die Möglichkeit",
  enterprise: "das Unternehmen",
  picture: "das Bild",
  book: "das Buch",
  water: "das Wasser",
  shape: "der Form",
  development: "die Entwicklung",
  month: "der Monat",
  family: "die Familie",
  morning: "der Morgen",
  evening: "der Abend",
  task: "die Aufgabe",
  university: "die Universität, Uni",
  sense: "der Sinn",
  state: "der Staat",
  destination: "das Ziel",
  boyfriend: "der Freund",
  topic: "das Thema",
  person: "die Person",
  night: "die Nacht",
  thing: "der Ding",
  room: "der Raum",
  look: "der Blick",
  number: "die Zahl",
  system: "das System",
  hour: "die Uhr",
  parents: "die Eltern",
  street: "die Straße",
  minute: "die Minute",
  group: "die Gruppe",
  value: "das Wert",
  face: "die Gesicht",
  language: "die Sprache",
  beginning: "der Anfang",
  place: "der Ort",
  moment: "der Moment",
  result: "die Folge",
  interest: "das Interesse",
  role: "die Rolle",
  door: "die Tür",
  student: "der Schüler",
  meaning: "die Bedeutung",
  text: "der Text",
  war: "der Krieg",
  manner: "die Weise",
  rule: "die Regierung",
  piece: "der Stück",
  apartment: "die Wohnung",
  conversation: "das Gespräch",
};

export const MEANINGS: {
  [key: string]: Words;
} = { VERBS, ADJECTIVES, NOUNS };
